### ISSUE TITLE
Disable verbose console logging?

### ISSUE THREAD

**Issue by philmitchell** [sematext/sematext-logsene-ios#22]
The new release is working great, with one small annoyance: In Xcode, the console is full of logs like:

```Rolling file
2020-12-06 14:15:12.864514-0800 APP[5819:157279] Opening new logs file
2020-12-06 14:15:12.865915-0800 APP[5819:157279] Starting log files directory cleanup
2020-12-06 14:15:12.866494-0800 APP[5819:157279] Deleting file sematext_logs_sdk_1607292852.863614
2020-12-06 14:16:12.864751-0800 APP[5819:157814] Rolling file
2020-12-06 14:16:12.865142-0800 APP[5819:157814] Opening new logs file
2020-12-06 14:16:12.866461-0800 APP[5819:157814] Starting log files directory cleanup
2020-12-06 14:16:12.867291-0800 APP[5819:157814] Deleting file sematext_logs_sdk_1605713011.9342098
2020-12-06 14:17:12.865333-0800 APP[5819:158437] Rolling file
2020-12-06 14:17:12.865710-0800 APP[5819:158437] Opening new logs file
2020-12-06 14:17:12.867074-0800 APP[5819:158437] Starting log files directory cleanup
2020-12-06 14:17:12.867827-0800 APP[5819:158437] Deleting file sematext_logs_sdk_1605711811.9245071
2020-12-06 14:18:12.866024-0800 APP[5819:159970] Rolling file
2020-12-06 14:18:12.866502-0800 APP[5819:159970] Opening new logs file
2020-12-06 14:18:12.869136-0800 APP[5819:159970] Starting log files directory cleanup
2020-12-06 14:18:12.870095-0800 APP[5819:159970] Deleting file sematext_logs_sdk_1607292972.8654451
```

Please disable the console logs or at least provide a verbosity setting. Thanks!

**Comment by gr0** [comment]
Hi @philmitchell - great to hear that the new release is working great. I think we can easily move those messages to only show  when debugging. I'll take care of that early next week and will release a new version of the library.

**Comment by gr0** [comment]
Hi @philmitchell I just released the [1.7.1](https://github.com/sematext/sematext-logsene-ios/releases/tag/1.7.1) version which should get rid of the logging, by moving it to DEBUG level. That should fix the problem.

**Comment by philmitchell** [comment]
Thanks @gr0 !

**Comment by philmitchell** [comment]
Hi @gr0, sorry I misunderstood before, but this doesn't fix the problem. `#if DEBUG` is true for me nearly always when I'm developing, which means that my Xcode logs are still full of sematext log output.

**Comment by gr0** [comment]
@philmitchell ahhh OK, I assumed the situation is only irritating when running the code on the target device. I'll adjust the logging, I can always add some more when I'll need. I should be able to release a new version in one or two days.

**Comment by philmitchell** [comment]
Thanks @gr0, sorry if I was unclear. Really appreciate the quick response!

**Comment by gr0** [comment]
No worries :) I just released version **1.7.2** which removes the excessive logging - https://github.com/sematext/sematext-logsene-ios/releases/tag/1.7.2

**Comment by philmitchell** [comment]
Awesome, working great now! Thanks @gr0!

**Comment by gr0** [comment]
Great, thanks for letting us know :)
